import '../models/movie.dart';

// Poster & backdrop từ TMDB, trailerKey từ YouTube (lấy qua TMDB API)
final movies = [
  Movie(
    id: 19995,
    title: "Avatar",
    poster: "https://image.tmdb.org/t/p/w500/6EiRUJpuoeQPghrs3YNktfnqOVh.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    description:
        "Trên thế giới Pandora tươi đẹp, một cựu lính thủy đánh bộ được giao nhiệm vụ thâm nhập vào cộng đồng người Na'vi. Khi anh dần gắn bó với họ, anh buộc phải lựa chọn giữa sứ mệnh và trái tim mình.",
    year: "2009",
    genre: "Hành động, Khoa học viễn tưởng",
    rating: "7.9",
    trailerKey: "5PSNL1qE6VY",
    episodes: [],
  ),
  Movie(
    id: 155,
    title: "The Dark Knight",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    description:
        "Batman đối mặt với Joker — kẻ thù hỗn loạn nhất từng xuất hiện ở Gotham. Cuộc chiến không chỉ là thể xác mà còn là cuộc thử thách về đạo đức và giới hạn của con người.",
    year: "2008",
    genre: "Hành động, Tội phạm",
    rating: "9.0",
    trailerKey: "EXeTwQWrcwY",
    episodes: [],
  ),
  Movie(
    id: 238,
    title: "The Godfather",
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLeFHIKV3LiV.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    description:
        "Bộ phim kinh điển về gia đình mafia Corleone. Khi ông trùm già bị ám sát, người con út Michael — vốn không muốn dính líu — dần trở thành thủ lĩnh quyền năng nhất trong thế giới ngầm.",
    year: "1972",
    genre: "Tội phạm, Chính kịch",
    rating: "9.2",
    trailerKey: "sY1S34973zA",
    episodes: [],
  ),
  Movie(
    id: 680,
    title: "Pulp Fiction",
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    description:
        "Những câu chuyện đan xen của hai sát thủ, một võ sĩ quyền anh, một ông trùm và vợ của hắn tạo nên bức tranh phi tuyến tính đầy bạo lực và hài hước đen.",
    year: "1994",
    genre: "Tội phạm, Chính kịch",
    rating: "8.9",
    trailerKey: "s7EdQ4FqbhY",
    episodes: [],
  ),
  Movie(
    id: 13,
    title: "Forrest Gump",
    poster: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/qdIMHd4sEoM9Y0RNvR2i0MBFMSr.jpg",
    description:
        "Qua đôi mắt của Forrest Gump — một người đàn ông có chỉ số IQ thấp nhưng trái tim vĩ đại — chúng ta chứng kiến những sự kiện lịch sử quan trọng nhất của nước Mỹ thế kỷ 20.",
    year: "1994",
    genre: "Chính kịch, Lãng mạn",
    rating: "8.8",
    trailerKey: "bLvqoHBptjg",
    episodes: [],
  ),
  Movie(
    id: 372058,
    title: "Your Name",
    poster: "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg",
    description:
        "Một chàng trai ở Tokyo và một cô gái ở vùng nông thôn bí ẩn hoán đổi thân xác cho nhau. Khi họ cố gắng tìm gặp nhau trong thực tế, họ phát hiện sự thật bất ngờ về số phận.",
    year: "2016",
    genre: "Hoạt hình, Lãng mạn",
    rating: "8.4",
    trailerKey: "xU47nhruN-Q",
    episodes: [],
  ),
  Movie(
    id: 475557,
    title: "Joker",
    poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/n6bUvigpRFqSwmPp1ZIz5LrVOx1.jpg",
    description:
        "Arthur Fleck — một diễn viên hài thất bại ở Gotham — dần chìm vào bóng tối. Câu chuyện về sự biến đổi từ con người bình thường thành tên tội phạm điên loạn nổi tiếng nhất lịch sử.",
    year: "2019",
    genre: "Tội phạm, Chính kịch",
    rating: "8.4",
    trailerKey: "zAGVQLHvwOY",
    episodes: [],
  ),
  Movie(
    id: 120,
    title: "The Lord of the Rings",
    poster: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/pIgHIEIVsaAqD0bGJsGBFRfHHVo.jpg",
    description:
        "Frodo Baggins cùng Hội Nhẫn lên đường phá hủy Chiếc nhẫn quyền năng trước khi bóng tối của Sauron nhấn chìm Trung Địa. Hành trình hùng tráng nhất trong lịch sử điện ảnh.",
    year: "2001",
    genre: "Phiêu lưu, Kỳ ảo",
    rating: "8.8",
    trailerKey: "V75dMMIW2B4",
    episodes: [],
  ),
  Movie(
    id: 244786,
    title: "Whiplash",
    poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg",
    description:
        "Andrew Neiman — tay trống tài năng tại nhạc viện danh tiếng — bị đẩy đến giới hạn bởi giáo viên khắc nghiệt Fletcher. Câu hỏi đặt ra: sự xuất chúng có đáng đổi bằng tất cả?",
    year: "2014",
    genre: "Âm nhạc, Chính kịch",
    rating: "8.5",
    trailerKey: "7d_jQycdQGo",
    episodes: [],
  ),
  Movie(
    id: 278,
    title: "The Shawshank Redemption",
    poster: "https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/iNh3BivHyg5sQRPP1KOkzguEX0H.jpg",
    description:
        "Andy Dufresne bị kết án oan vào tù Shawshank. Trong những năm tháng tối tăm đó, tình bạn và hy vọng trở thành ngọn lửa giúp anh tồn tại và vươn tới tự do.",
    year: "1994",
    genre: "Chính kịch",
    rating: "9.3",
    trailerKey: "6hB3S9bIaco",
    episodes: [],
  ),
  Movie(
    id: 496243,
    title: "Parasite",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    description:
        "Gia đình nghèo khó Ki-taek dần len lỏi vào cuộc sống của gia đình giàu có Park. Ranh giới giữa ký sinh và chủ nhân dần xóa nhòa trong tuyệt tác của đạo diễn Bong Joon-ho.",
    year: "2019",
    genre: "Chính kịch, Kinh dị",
    rating: "8.5",
    trailerKey: "5xH0HfJHsaY",
    episodes: [],
  ),
  Movie(
    id: 37854,
    title: "One Piece",
    poster: "https://image.tmdb.org/t/p/w500/fcXdJlbSqiIkFzz2OcRQVraBbOo.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2rmK7mnchw9Xr3XdiAwASoHiipo.jpg",
    description:
        "Monkey D. Luffy và băng hải tặc Mũ Rơm lên đường chinh phục đại dương để tìm kho báu One Piece và danh hiệu Vua Hải Tặc. Series anime huyền thoại với hơn 1000 tập.",
    year: "1999",
    genre: "Hoạt hình, Phiêu lưu",
    rating: "8.9",
    trailerKey: "S8_YwFLCh4U",
    episodes: [
      Episode(number: 1, title: "Tôi Là Luffy! Người Sẽ Trở Thành Vua Hải Tặc!"),
      Episode(number: 2, title: "Cậu Bé Có Chí Lớn! Sự Khởi Đầu Của Zoro"),
      Episode(number: 3, title: "Luffy Ra Khơi! Hành Trình Bắt Đầu"),
      Episode(number: 4, title: "Thị Trấn Hải Tặc Syrup Village"),
      Episode(number: 5, title: "Nami Gia Nhập Băng"),
      Episode(number: 6, title: "Trận Chiến Đầu Tiên Của Zoro"),
      Episode(number: 7, title: "Tiêu Diệt! Kẻ Thù Của Luffy"),
      Episode(number: 8, title: "Chiếc Thuyền Và Ước Mơ"),
    ],
  ),
];
